config = { 'raw_reads':
                '/home/laisepaixao/minionSeq/data/library',
           'dimension':
                '1d',
           'demux_dir':
                '/home/laisepaixao/minionSeq/data/library/demux',
           'basecalled_reads':
                '/home/laisepaixao/minionSeq/data/library/basecalled_reads',
            'build_dir':
                '/home/laisepaixao/minionSeq/data/library/build',
           'samples':
                ['ZK0152','031074','030292a','030292b','030292c','NTC'],
           'guppy_config':
                'dna_r9.4.1_450bps_hac.cfg',
           'prefix':
                'LIB',
           'ref_genome':
                '/home/laisepaixao/minionSeq/pipeline/refs/ref.fasta',
           'primer_scheme':
                '/home/laisepaixao/minionSeq/pipeline/metadata/primers.bed'
        }