config = { 'raw_reads':
                '/home/laisepaixao/softwares/minionSeq/data/zika-library12-2019-05-22/',
           'dimension':
                '1d',
           'demux_dir':
                '/home/laisepaixao/softwares/minionSeq/data/zika-library12-2019-05-22/demux',
           'basecalled_reads':
                '/home/laisepaixao/softwares/minionSeq/data/basecalled_reads',
            'build_dir':
                '/home/laisepaixao/softwares/minionSeq/build',
           'samples':
                ['TRDP173','TRDP238','TRDP252','TRDP256','TRDP274','NTC12'],
           'guppy_config':
                'dna_r9.4.1_450bps_hac.cfg',
           'prefix':
                'LIB12',
           'ref_genome':
                '/home/laisepaixao/softwares/minionSeq/pipeline/refs/ref_zika_KJ776791.fasta',
           'primer_scheme':
                '/home/laisepaixao/softwares/minionSeq/pipeline/metadata/ZIKA_v2_500.amplicons.ver2.bed'
        }
