#!/bin/bash
# Install minion-seq requirements
echo ">> minion-seq requirements <<" && echo ""
# Install packages: curl git htop libdeflate-dev nanopolish wget
sudo apt install curl git htop libdeflate-dev nanopolish wget
# Guppy
if [ -z "$(which guppy_basecaller)" ]
then
#  GUPPY CPU
#  echo "Downloading Guppy..."
#  curl https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy-cpu_3.4.4_linux64.tar.gz --output $HOME/softwares/ont-guppy-cpu.tar.gz
#  echo "Installing Guppy..."
#  cd $HOME/softwares/ && tar -vzxf ont-guppy-cpu.tar.gz && mv ont-guppy-cpu/ guppy-cpu/ && rm -rf ont-guppy-cpu.tar.gz
#  export PATH="$HOME/softwares/guppy-cpu/bin:/usr/local/share/rsi/idl/bin:$PATH"
#  echo 'export PATH="$HOME/softwares/guppy-cpu/bin:/usr/local/share/rsi/idl/bin:$PATH"' >> $HOME/.bashrc
#  echo "Successfully installed Guppy!" && echo ""
# GUPPY GPU
  echo "Downloading Guppy..."
  curl https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_3.4.4_linux64.tar.gz --output $HOME/softwares/ont-guppy-gpu.tar.gz
  echo "Installing Guppy..."
  cd $HOME/softwares/ && tar -vzxf ont-guppy-gpu.tar.gz && mv ont-guppy/ guppy-gpu/ && rm -rf ont-guppy-gpu.tar.gz
  export PATH="$HOME/softwares/guppy-gpu/bin:/usr/local/share/rsi/idl/bin:$PATH"
  echo 'export PATH="$HOME/softwares/guppy-gpu/bin:/usr/local/share/rsi/idl/bin:$PATH"' >> $HOME/.bashrc
  echo "Successfully installed Guppy!" && echo ""
else
  echo "Guppy already installed!" && echo ""
fi
# Miniconda
if [ -z "$(which conda)" ]
then
  echo "Downloading Miniconda..."
  curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh --output $HOME/softwares/miniconda.sh
  echo "Installing Miniconda..."
  bash $HOME/softwares/miniconda.sh -bfp $HOME/softwares/conda && rm --recursive --force $HOME/softwares/miniconda.sh
  export PATH="$HOME/softwares/conda/bin:/usr/local/share/rsi/idl/bin:$PATH"
  echo 'export PATH="$HOME/softwares/conda/bin:/usr/local/share/rsi/idl/bin:$PATH"' >> $HOME/.bashrc
  conda config --add channels r
  conda config --add channels biobuilds
  conda config --add channels conda-forge
  conda config --add channels anaconda
  conda config --add channels bioconda
  echo "Successfully installed Miniconda!" && echo ""
else
  echo "Miniconda already installed!" && echo ""
fi
# Updating conda
echo "Updating conda..."
conda update --yes --name base conda
# Create conda environment: minion-seq
echo "Creating "minion-seq" environment..."
conda create --yes --name minion-seq
echo "Installing packages in minion-seq..."
conda install --yes --name minion-seq biopython boto boto3 bwa drmaa ipython libiconv libdeflate ncurses numpy pandas porechop psutil pycoqc pysam python=3.6* pyvcf r r-minionqc r-optparse r-reshape r-reshape2 samtools seqtk snakemake vcftools
# Create PATH to bin folder
echo "Creating PATH to bin folder..."
cp -f -r -u $HOME/softwares/minion-seq/bin/ $HOME/bin/ && \
chmod 777 -R $HOME/bin/ && \
export PATH="$HOME/bin:/usr/local/share/rsi/idl/bin:$PATH" >> $HOME/.bashrc && \
echo 'export PATH="$HOME/bin:/usr/local/share/rsi/idl/bin:$PATH"' >> $HOME/.bashrc
echo "" && echo "Done!"
