name: minion-seq_pipeline
channels:
  - anaconda
  - biobuilds
  - bioconda
dependencies:
  - biopython
  - bwa
  - fastx-toolkit
  - nanopolish
  - pysam
  - python
  - pyvcf
  - R
  - r-optparse
  - r-reshape
  - samtools
  - vcftools
