name: minion-seq_pipeline
channels:
  - conda-forge
  - bioconda
  - biobuilds
  - r
  - defaults
dependencies:
  - biopython
  - bwa
  - fastx-toolkit
  - nanopolish=0.9.0
  - pysam
  - python
  - pyvcf
  - R
  - r-optparse
  - r-reshape
  - samtools
  - vcftools
