name: minion-seq
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - biopython
  - boto
  - boto3
  - drmaa
  - ipython
  - numpy
  - pandas
  - pip
  - porechop
  - psutil
  - pysam
  - python=3.6
  - snakemake

